---
title: "oysterfig2"
output: html_document
---
Rmd to make pie figure of detected proteins GOslim terms (**Fig. 2** in paper). 

`ggrepel` to help get GOslim terms to not overlap in final pie
```{r}
library(ggrepel)
```

```{r}
install.packages("viridis")
```

```{r}
library(viridis)
```
Read in the GOslim pie table made in notebook [02-detected-prots-annotate-GOslim.ipynb](https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/notebooks/02-detected-prots-annotate-GOslim.ipynbhttps://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/notebooks/02-detected-prots-annotate-GOslim.ipynb)
```{r}
piecounts <- read.csv("../analyses/Fig2-pie/GOslim-P-pie-detectedprots.txt", header = FALSE)
head(piecounts)
```

Set pie colors:
```{r}
piecolors <- rainbow(14)
```

### Pretty pie chart: 
Got code from the stackoverflow answer linked here:       
https://stackoverflow.com/questions/53227164/how-can-i-avoid-pie-chartlegend-overlap-in-r 

```{r}
structure(c('other biological processes' = 206L, 'other metabolic processses' = 175L, 'cell organization and biogenesis' = 150L, 'developmental processes' = 149L, 'transport' = 102L, 'protein metabolism' = 94L, 'RNA metabolism' = 84L, 'signal transduction' = 79L, 'stress reponse' = 72L, 'cell cycle and proliferation' = 68L, 'death' = 25L, 'cell-cell signaling' = 20L, 'cell adhesion' = 19L, 'DNA metabolism' = 13L), .Dim = 14L, .Dimnames = list(. = c("other biological process", "other metabolic processes", "cell organization and biogenesis", "developmental processes", "transport", "protein metabolism", "RNA metabolism", "signal transduction", "stress response", "cell cycle and proliferation", "death", "cell-cell signaling", "cell adhesion", "DNA metabolism")), class = "table") -> Type
#sort Type 
Type <- sort(Type, decreasing = TRUE) 
piepercent <- round(Type/sum(Type)*100)
par(mar = c(1, 1, 1, 1)) 

pie(
  Type, 
  edges = 200, 
  radius = 0.65,
  clockwise = TRUE, # IMPORTANT
  angle = 45, 
  col = viridis::viridis_pal(option = "magma", direction=-1)(length(Type)),  # BETTER COLOR PALETTE
  labels = piepercent, # NEVER DISPLAY OVERLAPPING LABELS
  cex = 0.7
)

legend(
  x = 0.80, # DELIBERATE POSITION
  y = 0.5, # DELIBERATE POSITION
  inset = .05, 
  legend = names(Type), # YOU WERE PASSING IN _ALL_ THE REPEAT NAMES
  fill = viridis::viridis_pal(option = "magma", direction=-1)(length(Type)),  # USE THE SAME COLOR PALETTE
  horiz = FALSE,
  cex = 0.65, # PROPER PARAMETER FOR TEXT SIZE
  text.width = 0.8 # SET THE BOX WIDTH
)
```

Save pie as pdf to analyses:
```{r}
pdf("../analyses/Fig2-pie/detectedprots-GOslim-pie.pdf")
structure(c('other biological processes' = 206L, 'other metabolic processses' = 175L, 'cell organization and biogenesis' = 150L, 'developmental processes' = 149L, 'transport' = 102L, 'protein metabolism' = 94L, 'RNA metabolism' = 84L, 'signal transduction' = 79L, 'stress reponse' = 72L, 'cell cycle and proliferation' = 68L, 'death' = 25L, 'cell-cell signaling' = 20L, 'cell adhesion' = 19L, 'DNA metabolism' = 13L), .Dim = 14L, .Dimnames = list(. = c("other biological process", "other metabolic processes", "cell organization and biogenesis", "developmental processes", "transport", "protein metabolism", "RNA metabolism", "signal transduction", "stress response", "cell cycle and proliferation", "death", "cell-cell signaling", "cell adhesion", "DNA metabolism")), class = "table") -> Type
#sort Type 
Type <- sort(Type, decreasing = TRUE) 
piepercent <- round(Type/sum(Type)*100)
par(mar = c(1, 1, 1, 1)) 

pie(
  Type, 
  edges = 200, 
  radius = 0.65,
  clockwise = TRUE, # IMPORTANT
  angle = 45, 
  col = viridis::viridis_pal(option = "magma", direction=-1)(length(Type)),  # BETTER COLOR PALETTE
  labels = piepercent, # NEVER DISPLAY OVERLAPPING LABELS
  cex = 0.7
)

legend(
  x = 0.80, # DELIBERATE POSITION
  y = 0.5, # DELIBERATE POSITION
  inset = .05, 
  legend = names(Type), # YOU WERE PASSING IN _ALL_ THE REPEAT NAMES
  fill = viridis::viridis_pal(option = "magma", direction=-1)(length(Type)),  # USE THE SAME COLOR PALETTE
  horiz = FALSE,
  cex = 0.65, # PROPER PARAMETER FOR TEXT SIZE
  text.width = 0.8 # SET THE BOX WIDTH
)
```






